name: Mars GPU CI Core

on:
  push:
    branches:
      - '*'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build mars
        shell: bash
        run: |
          python setup.py build_ext -i

      - name: Run GPU CI
        shell: bash
        run: |
          /opt/conda/bin/coverage run -m pytest ./ -m cuda
          /opt/conda/bin/coverage combine
          /opt/conda/bin/coverage xml

      - name: Report coverage data
        shell: bash
        run: |
          bash <(curl -s https://codecov.io/bash)